### ISSUE TITLE
How to build the library_path

### ISSUE THREAD

**Issue by yongchangli** [idaholab/pika#134]
When I running pika/problems/1D_full/1D_full.i by moose, the error always shows that

*** ERROR ***
A 'ChemicalPotentialIC' is not a registered object.

We loaded objects from the following libraries and still couldn't find your object:
(NONE)

Make sure you have compiled the library and either set the "library_path" variable in your input file or exported "MOOSE_LIBRARY_PATH".

But I can find the ChemicalPotentialIC.lo in pika/src/ics.

It's my first time to use moose, it confused me more than two weeks, I hope some one can help me to solve it.
How can I solve this problem? How to add the library_path to pika?
[1D_full.txt](https://github.com/idaholab/pika/files/1319726/1D_full.txt)

**Comment by aeslaughter** [comment]
This input file is out of date and should be removed from the repository. If you are just trying to understand MOOSE you should do the following.

1. [Build MOOSE](http://www.mooseframework.org/getting-started/)
2. [Create an App](http://www.mooseframework.org/create-an-app/)
3. [Work through Tutorial](http://mooseframework.org/wiki/MooseTutorials/DarcyThermoMechanical/)

Pika is an application for a very specific problem, you should only try to use it if you are working on snow microstructure evolution.

**Comment by aeslaughter** [comment]
Thanks for telling me about the problem, I created an issue (#135) specific to these input files.

**Comment by yongchangli** [comment]
Thanks for your help!
